### ISSUE TITLE
[special effect] gradient border

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#145]
https://x.com/jh3yy/status/1800608072391340255

<img width="432" alt="image" src="https://github.com/magicuidesign/magicui/assets/16860528/60dc111d-08e7-48b1-a138-a93f8ab7c28b">

We should make an easy to use example using react + typescript + tailwindcss which people can copy + paste into their apps

bonus points for props with configurability

**Comment by DoffuXx** [comment]
can you assign me

**Comment by DoffuXx** [comment]
Hi, I have made the component, but I didn't follow his CSS 100% because I encountered problems with Tailwind; it doesn't support that CSS. So, I made it similar to the example. What do you think?

![image](https://github.com/magicuidesign/magicui/assets/96635567/ea8974b5-7f46-4ae1-a87f-41a289ad5be9)
Here's The code 
![image](https://github.com/magicuidesign/magicui/assets/96635567/219dede3-0e64-45a3-8174-e98986f181e5)
