### ISSUE TITLE
`hexToRGB`  function could be utility function and can be used by several components

### ISSUE THREAD

**Issue by alamenai** [magicuidesign/magicui#159]
Hi @dillionverma ,

While I was reading the code of Particles component, I found this function :

```ts
function hexToRgb(hex: string): number[] {
  hex = hex.replace("#", "");
  const hexInt = parseInt(hex, 16);
  const red = (hexInt >> 16) & 255;
  const green = (hexInt >> 8) & 255;
  const blue = hexInt & 255;
  return [red, green, blue];
}
```

I guess it could a utility function that can be used by several components.

**Comment by dillionverma** [comment]
appreciate it! where else would you use this?

**Comment by alamenai** [comment]
Hi @dillionverma , it's already found on Particles but we can extract it for potential usage in other components as utility function.

**Comment by dillionverma** [comment]
Perfect! I took a deeper look into the components but I don't think there is a strong need for this based on initial evaluation since most components which take colour props can also take RGB input value. Particles component in particular was unique since that was the only one which needed to access the RGB values to render circles on canvas.

Going to close issue for now but let me know if you come across any other stronger usecases!
