### ISSUE TITLE
[bug]: /docs/components/sparkles-text

### ISSUE THREAD

**Issue by maximilianvb** [magicuidesign/magicui#267]
**Describe the bug**
The example doesn't work at all.

**Comment by Draxx0** [comment]
Hi there! @maximilianvb 

Could you be more specific? On my end it works fine, did you install it via the CLI? if so, did you try adding it manually?

**Comment by owenmorgan** [comment]
same for me - using CLI it doesnt work. you see the text but no sparkle

**Comment by Draxx0** [comment]
Hey @owenmorgan 

Nop, there is no code required in the tailwindconfig

Have you also tried to adding the component manually ?

Have a nice day ! :D

**Comment by Draxx0** [comment]
I tried to install the component using the cli, i found that the "npx magicui-cli add sparkles-text" doesn't work for me.

There is a fix that works for me :

Instead of using the npx magicui-cli add sparkles-text, you can use the : 

`npx magicui-cli add`

Then you can select the sparkles-text component.

Let me know if it works for you guys.

**Comment by dillionverma** [comment]
Just tested this using the latest cli and works! :) 

```
pnpm dlx shadcn@latest add "https://magicui.design/r/sparkles-text" 
```

Feel free to re-open issue if anyone experiences again
