### ISSUE TITLE
Client side exception

### ISSUE THREAD

**Issue by shubhamku044** [magicuidesign/magicui#320]
**Describe the bug**

**To Reproduce**
1. Go to 'magicui website'
2. Click on 'bunch of different components and then at the end click on globe component'
3. See error

**Expected behavior**
After I clicked on globe component, I got this screen

**Screenshots**
![image](https://github.com/user-attachments/assets/a015a459-d446-4308-8da3-cf10a789923d)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser safaru

**Comment by itsarghyadas** [comment]
I am using Chrome and Windows. I tried all the steps to reproduce the error, but at least it works fine for me. This is a known deploying error from our side. Sorry for the issue, but it should be fixed by now.

Feel free to let me know if you have any more questions. Otherwise, I will close this issue.

Thank you.

**Comment by shubhamku044** [comment]
> I am using Chrome and Windows. I tried all the steps to reproduce the error, but at least it works fine for me. This is a known deploying error from our side. Sorry for the issue, but it should be fixed by now.
> 
> Feel free to let me know if you have any more questions. Otherwise, I will close this issue.
> 
> Thank you.

No I don't have any questions, you can close the issue, Thanks
