### ISSUE TITLE
[bug]: /docs/components/meteors

### ISSUE THREAD

**Issue by Vasanth-sharp** [magicuidesign/magicui#360]
**Describe the bug**
Bug i found that meteor is not working properly kindly clear the bug,it doesn't fell down 
**To Reproduce**

**Expected behavior**
Expected behavior that meteor should fell down,it doesn't happening 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by notREKASH** [comment]
Hello,

Thank you for reporting this issue. To better understand the problem and help you resolve it, could you please provide a few more details?

- Bug description: You mentioned that "the meteor doesn't fall." Could you clarify when and in what context this happens? Does it occur during a specific interaction (click, page load, etc.)?
- Steps to reproduce: Could you detail the exact steps to reproduce the issue? This will help us replicate and analyze the problem.
- Expected behavior: You mentioned that you expect the meteor to fall. Could you describe more precisely what behavior you're expecting? For example, is it an animation, a movement of an element on the page, or something else?
- Environment: Don't forget to include your operating system, browser, and their versions so we can test in a similar setup to yours.

If possible, attaching screenshots or videos could also be helpful.

Thanks in advance for these details, they will help us resolve the issue faster!

**Comment by EdamAme-x** [comment]
@Vasanth-sharp It seems that styles are not automatically added to tailwind.config.js. You can fix this by looking at the Manual and adding them yourself.

**Comment by Vasanth-sharp** [comment]
Ok, I'll check it out and thank you for your response

**Comment by Vasanth-sharp** [comment]
I couldn't find any manual in magic ui,i could find the cli and manual only

**Comment by EdamAme-x** [comment]
![image](https://github.com/user-attachments/assets/eb42dc43-f2e8-440a-9b91-e730ee1c4f2b)

**Comment by Vasanth-sharp** [comment]
Thanks, I'll check it out.

**Comment by dillionverma** [comment]
Closing this issue for now! Let me know if this is still a problem
