### ISSUE TITLE
Can we get a figma for visualisation purposes please? 

### ISSUE THREAD

**Issue by skandshekatkar** [magicuidesign/magicui#377]
**Is your feature request related to a problem? Please describe.**
I am a designer and I'd love to be able to use these components in my projects. But I don't code like many other designers. I want to be able to visualise these components in my own theme / fonts / use cases etc. so that my team can develop it accordingly. 

**Describe the solution you'd like**
Perhaps a figma file that has these components, even static versions would suffice. This way I'd be able to demonstrate the designs in the appropriate use cases with custom themes to the team for approval before it goes into dev. 

**Describe alternatives you've considered**
If not a figma file, a way to at least theme the components and view them so that I can grab screenshots from the website and use it in my design demos maybe?

**Additional context**
Google's Material design system for example has interactive components on their website but they also have a static version of all the components available as a figma file published to the community. I think this could boost collaboration and promote designers to use this library in their work too. This is a major a workflow issue that is currently limiting my use of this library.

**Comment by dillionverma** [comment]
Hi!

This is an interesting idea but difficult in practice since "animated landing page components" isn't really standardized in any way. It's more of a cherry-picked collection of effects and animations. 

Definitely appreciate the interest and I think it'd be a really good idea but I won't be able to support it myself at the current moment.

However, I'm really open to any contributions from the community!
