### ISSUE TITLE
[Developer Experience] We need to enforce linting / formatting standards

### ISSUE THREAD

**Issue by dillionverma** [magicuidesign/magicui#80]
Can someone make a PR to enforce prettier + eslint standards so that all new PRs have the same format?

We might need some sort of lint on commit or lint on deploy flow. 

Need some input from the community on best developer experience

https://github.com/shadcn-ui/ui is a good standard to refer to imo

**Comment by itsarghyadas** [comment]
```
Contentlayer config change detected. Updating type definitions and data...
Warning: Found 17 problems in 43 documents.

 └── 17 documents contain field data which didn't match the structure defined in the document type definition. (Skipping documents)

     • "docs/changelog.mdx" of type "Doc" has the following incompatible fields:
       • published: "false\r"  
```

We also need a better pre-commit hook since our contributors use different operating systems. We need to establish a standard rule to ensure consistency across all OS systems.

This error can be temporarily resolved by changing your Git configuration with the command `git config --global core.autocrlf false`. Linux and Mac have a different end-of-line system than Windows, so converting to CRLF is causing the error. Setting `autocrlf` to false will use the end-of-line format as it is in the GitHub repo, which should solve the issue.

However, I recommend re-cloning the entire repo from scratch after changing the settings. Additionally, restart your terminal, code editor, and ideally, your PC or laptop.

**Comment by itsarghyadas** [comment]
```
Contentlayer config change detected. Updating type definitions and data...
Warning: Found 17 problems in 43 documents.

 └── 17 documents contain field data which didn't match the structure defined in the document type definition. (Skipping documents)

     • "docs/changelog.mdx" of type "Doc" has the following incompatible fields:
       • published: "false\r"
```

We also need a better pre-commit hook since our contributors use different operating systems. We need to establish a standard rule to ensure consistency across all OS systems.

This error can be temporarily resolved by changing your Git configuration with the command `git config --global core.autocrlf input`. Linux and Mac have a different end-of-line system than Windows, so converting to CRLF is causing the error. Setting `autocrlf` to input will use the end-of-line format as it is in the GitHub repo, which should solve the issue.

However, I recommend re-cloning the entire repo from scratch after changing the settings. Additionally, restart your terminal, code editor, and ideally, your PC or laptop.

**Comment by abdrahmanES1** [comment]
@dillionverma can you assign it to me

**Comment by dillionverma** [comment]
merged!

closing for now
